spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        #Product service rout
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**

        #Product service rout
        - id: vendor-service
          uri: lb://vendor-service
          predicates:
            - Path=/api/vendors/**

        #Product service rout
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/api/store/**


        #Discovery server route
        - id: discovery-server
          uri: http://murethi-discovery-server:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        #Discovery server static files route
        - id: discovery-server-static
          uri: http://murethi-discovery-server:8761
          predicates:
            ##line below serves static files from eureka server css,js,images using localhost:port/eureka
            - Path=/eureka/**
#Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://murethi-discovery-server:8761/eureka
  instance:
    hostname: localhost
#Eureka Routes
#Application Logging
logging:
  level:
    root: INFO
    springframework:
      cloud:
        - gateway: -TRACE
        - gateway:
            route:
              RouteDefinitionLocator: INFO