server:
  port: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  servlet:
    contextPath: /api/store/


eureka:
  client:
    serviceUrl:
      defaultZone: http://murethi-discovery-server:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    trace: DEBUG
spring:
  webflux:
    base-path: /api/store/
  application:
    name: store-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

