server:
  port: 0
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  servlet:
    contextPath: /api/store/


eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

logging:
  level:
    trace: DEBUG
spring:
  webflux:
    base-path: /api/store/
  application:
    name: store-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/brandlogs_products
    username: kodix
    password: Kodix#2022
    driver-class-name: com.mysql.cj.jdbc.Driver

